[functions]
directory = "functions"

[[redirects]]
from = "/screenshot/1.0/:url/"
to = "/.netlify/functions/screenshot"
status = 200
force = true

[[redirects]]
from = "/screenshot/1.0/:url/:aspectratio/"
to = "/.netlify/functions/screenshot"
status = 200
force = true

[[redirects]]
from = "/screenshot/1.0/:url/:aspectratio/:size/"
to = "/.netlify/functions/screenshot"
status = 200
force = true