[functions]
directory = "functions"
node_bundler = "esbuild"
external_node_modules = ["chrome-aws-lambda"]

[[redirects]]
from = "/screenshot/*"
to = "/.netlify/functions/screenshot"
status = 200
force = true
